#!/usr/bin/env python3
"""Generate the Obsidian Kanban board from Foreman task files.

  board.py [--root .foreman]

The board is a DERIVED view. Task files are the source of truth, so this file can
be deleted and regenerated at any time. Cards are wikilinks rather than inline
text, which keeps the board thin and stops the Obsidian plugin and Foreman from
fighting over the same content.

Format notes, verified byte-exact against a real board written by the plugin:
  - frontmatter is --- / blank / kanban-plugin: board / blank / ---
  - lanes are level-2 headings, one blank line before the first card
  - two blank lines between the last card of a lane and the next heading
  - the settings block emits only {"kanban-plugin":"board"}; the plugin adds
    list-collapse itself, and a hand-written array of the wrong length misrenders
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from foreman_lib import all_sessions, all_tasks, parse_critique, critique_is_clear  # noqa: E402

LANES = [
    ("backlog", "Backlog"),
    ("planned", "Planned"),
    ("in_progress", "In Progress"),
    ("in_test", "In Test"),
    ("beta", "Beta"),
    ("awaiting_human", "Awaiting Human"),
    ("done", "Done"),
    ("blocked", "Blocked"),
]


def card(task: dict, live: dict[str, dict]) -> str:
    checked = "x" if task["status"] == "done" else " "
    bits = [f"- [{checked}] [[{task['path'].stem}]]"]

    tags = []
    if task["parallel"]:
        tags.append("#parallel")
    if task["needs_clarification"]:
        tags.append("#needs-clarification")
    if task["acceptance_total"]:
        tags.append(f"#ac-{task['acceptance_done']}of{task['acceptance_total']}")

    sess = live.get(task["session"])
    if sess:
        state = sess.get("state", "")
        if state in ("stuck", "overdue"):
            tags.append(f"#{state}")
        pct = sess.get("context_pct")
        if isinstance(pct, (int, float)) and pct >= sess.get("compact_pct", 55):
            tags.append("#compacting")

    if tags:
        bits.append("  " + " ".join(tags))
    return "\n".join(bits)


def render(root: Path) -> str:
    tasks = all_tasks(root)
    live = {s["name"]: s for s in all_sessions(root) if s.get("name")}

    out = ["---", "", "kanban-plugin: board", "", "---", ""]
    for key, label in LANES:
        out.append(f"## {label}")
        out.append("")
        for t in [t for t in tasks if t["status"] == key]:
            out.append(card(t, live))
        out.append("")
        out.append("")

    out.append('%% kanban:settings')
    out.append("```")
    out.append('{"kanban-plugin":"board"}')
    out.append("```")
    out.append("%%")
    return "\n".join(out) + "\n"


LANE_ICON = {"backlog": "○", "planned": "◔", "in_progress": "◑", "in_test": "◕",
             "beta": "◕", "awaiting_human": "⏸", "done": "●", "blocked": "✕"}


def bar(done: int, total: int, width: int = 20) -> str:
    """A progress bar made of block characters — renders identically everywhere."""
    if not total:
        return "░" * width
    filled = round(width * done / total)
    return "█" * filled + "░" * (width - filled)


def render_status(root: Path) -> str:
    """The team-facing view. Plain GitHub-Flavored Markdown, no wikilinks.

    This is the file a teammate opens. board.md is Obsidian-only — its [[links]]
    render as literal text on GitHub — and dashboard.html needs a browser and a
    clone. Everything here renders in a repo browser, VS Code, and Obsidian alike.
    """
    tasks = all_tasks(root)
    total = len(tasks)
    done = [t for t in tasks if t["status"] == "done"]
    ac_t = sum(t["acceptance_total"] for t in tasks)
    ac_d = sum(t["acceptance_done"] for t in tasks)
    pct = round(100 * len(done) / total) if total else 0

    out = ["# Status", "",
           "<!-- Generated by /foreman:board. Do not hand-edit — regenerate it. -->", "",
           f"`{bar(len(done), total)}` **{len(done)}/{total} tasks** ({pct}%) · "
           f"**{ac_d}/{ac_t} acceptance criteria met**", ""]

    blocked = [t for t in tasks if t["status"] == "blocked"]
    waiting = [t for t in tasks if t["status"] == "awaiting_human"]
    crit = parse_critique(root / "CRITIQUE.md")
    g2_rows: list[tuple[str, str]] = []
    if crit["exists"] and not critique_is_clear(crit):
        for f in crit["findings"]:
            if f.get("status") == "open":
                g2_rows.append((f"{f['id']} {f.get('title', '')}".strip(),
                                "G2 finding open"))
        if crit.get("re_critique") == "pending":
            g2_rows.append(("G2 re-critique", "pending — re-invoke `/foreman:critique`"))
        if not g2_rows:
            why = (crit["problems"][0] if crit.get("problems")
                   else "not G2-clear")
            g2_rows.append(("CRITIQUE.md", why))
    if blocked or waiting or g2_rows:
        out += ["## Needs attention", "", "| | Item | Why |", "|---|---|---|"]
        for t in blocked:
            out.append(f"| 🔴 | {link(t, root)} | blocked |")
        for t in waiting:
            why = "needs clarification" if t["needs_clarification"] else "awaiting a decision"
            out.append(f"| 🟠 | {link(t, root)} | {why} |")
        for item, why in g2_rows:
            out.append(f"| 🟠 | {item} | {why} |")
        out.append("")
    else:
        out += ["Nothing is blocked or waiting on a person.", ""]

    out += ["## Board", ""]
    for key, label in LANES:
        items = [t for t in tasks if t["status"] == key]
        if not items:
            continue
        out += [f"### {LANE_ICON.get(key, '·')} {label} ({len(items)})", "",
                "| Task | Criteria | Depends on | Estimate |", "|---|---|---|---|"]
        for t in items:
            ac = f"{t['acceptance_done']}/{t['acceptance_total']}" if t["acceptance_total"] else "—"
            par = " `[P]`" if t["parallel"] else ""
            out.append(f"| {link(t, root)}{par} | {ac} | {t['depends_on'] or '—'} "
                       f"| {t['estimate'] or '—'} |")
        out.append("")

    empty = [label for key, label in LANES if not any(t["status"] == key for t in tasks)]
    if empty:
        out += [f"_Empty: {', '.join(empty)}._", ""]

    out += ["---", "",
            "Task files carry the full detail — the why, the build notes, the acceptance "
            "criteria and the verify output that proved them.",
            "",
            "`board.html` is the same board with a visual layout (open it in a browser). "
            "`board.md` is a drag-and-drop board in Obsidian."]
    return "\n".join(out) + "\n"


def link(task: dict, root: Path) -> str:
    """A relative markdown link that resolves in a repo browser and in an editor."""
    rel = task["path"].relative_to(root).as_posix()
    return f"[{task['id']} {task['title']}]({rel})"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".foreman")
    a = ap.parse_args()
    root = Path(a.root).resolve()
    if not root.is_dir():
        sys.exit(f"board.py: no such directory: {root}")
    target = root / "board.md"
    target.write_text(render(root))
    status = root / "STATUS.md"
    status.write_text(render_status(root))
    n = len(all_tasks(root))
    print(f"wrote {target} and {status} ({n} task{'s' if n != 1 else ''})")
